services:
  investment-assistant:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - OLLAMA_BASE_URL=http://ollama:11434
      - OLLAMA_MODEL=llama3.2:3b
      - ENABLE_CACHING=true
      - LOG_LEVEL=INFO
      - MAX_REQUESTS_PER_MINUTE=100
    volumes:
      - app_data:/app/data
    depends_on:
      - ollama
    restart: unless-stopped
    
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

volumes:
  app_data:
  ollama_data:
